# Generated by Django 2.0.1 on 2018-01-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('injury_type', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=400)),
                ('bench_date', models.DateTimeField(verbose_name='date benched')),
                ('unbench_date', models.DateTimeField(verbose_name='date unbenched')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('bucket_name', models.CharField(max_length=200)),
            ],
        ),
    ]
